/* ============================= VEHICLE INSPECTION REPORT (shared with customer) ============================= */
// Reached by opening the link generated by "Share Report" in the staff
// inspection modal: ?inspect=<jobId>&token=<inspectionToken> -- no login
// required (see initApp() in sync-engine.js for the URL detection, and
// kiosk_inspection_report()/kiosk_submit_inspection_signature() in
// backend/schema.sql for the two narrow anonymous-safe RPCs this screen
// calls). The per-job token is what stops a stranger from viewing/signing
// a report just by guessing a job id -- they'd need the exact link shared
// by the shop.
function renderInspectionReport(){
  const en = state.language==='en';
  const report = state.inspectReport;
  const severityLabel = en
    ? {ok:'OK', attention:'Needs Attention', replace:'Needs Replacement'}
    : {ok:'OK', attention:'Perlu Perhatian', replace:'Perlu Tukar'};
  const severityClass = {ok:'pill-done', attention:'pill-wait', replace:'pill-low'};
  let body = '';
  if(report==='loading'){
    body = `<p style="text-align:center;color:var(--text-muted);">${en?'Loading your inspection report…':'Memuatkan laporan pemeriksaan anda…'}</p>`;
  } else if(report==='invalid'){
    body = `<div class="empty">${ICONS.alert}<div>${en?'This report link is invalid or has expired. Ask the workshop for a fresh link.':'Pautan laporan ini tidak sah atau telah tamat tempoh. Minta pautan baharu daripada bengkel.'}</div></div>`;
  } else if(report){
    const items = Object.entries(report.inspection||{});
    const marks = report.diagramMarks||[];
    body = `
      <div style="text-align:left;">
        <div style="font-family:'IBM Plex Mono',monospace;font-size:12px;color:var(--text-muted);">${esc(report.jobNo)}</div>
        <div style="font-size:16px;font-weight:700;margin:4px 0 12px;">${esc(report.plate||'-')} ${report.model?'· '+esc(report.model):''}</div>

        ${items.length ? `
        <div style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.03em;color:var(--text-muted);margin-bottom:6px;">${en?'Inspection Checklist':'Senarai Semak Pemeriksaan'}</div>
        <div style="display:flex;flex-direction:column;gap:5px;margin-bottom:16px;">
          ${items.map(([name,st])=>`<div style="display:flex;justify-content:space-between;align-items:center;padding:7px 10px;background:var(--panel-alt);border-radius:6px;">
            <span style="font-size:12.5px;">${tt(name)}</span>
            <span class="pill ${severityClass[st]}">${severityLabel[st]}</span>
          </div>`).join('')}
        </div>` : ''}

        ${marks.length ? `
        <div style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.03em;color:var(--text-muted);margin-bottom:6px;">${en?'Points Marked on Vehicle':'Titik Ditandakan pada Kenderaan'}</div>
        <div style="display:flex;flex-direction:column;gap:5px;margin-bottom:16px;">
          ${marks.map((m,idx)=>`<div style="display:flex;gap:8px;align-items:center;padding:7px 10px;background:var(--panel-alt);border-radius:6px;">
            <span class="pill ${severityClass[m.severity]}" style="min-width:20px;text-align:center;">${idx+1}</span>
            <span style="font-size:12.5px;flex:1;">${esc(m.note||severityLabel[m.severity])}</span>
          </div>`).join('')}
        </div>` : ''}

        ${(report.photos||[]).length ? `
        <div style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.03em;color:var(--text-muted);margin-bottom:6px;">${en?'Photos':'Gambar'}</div>
        <div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px;">
          ${report.photos.map((p,idx)=>`<img src="${p}" alt="${en?'Vehicle photo':'Gambar kenderaan'} ${idx+1}" style="width:72px;height:72px;object-fit:cover;border-radius:6px;border:1px solid var(--border);">`).join('')}
        </div>` : ''}

        ${!items.length && !marks.length && !(report.photos||[]).length ? `<div class="empty" style="padding:12px 0;">${en?'No inspection findings recorded yet.':'Belum ada dapatan pemeriksaan direkodkan.'}</div>` : ''}

        <div style="border-top:1px dashed var(--border);padding-top:14px;margin-top:4px;">
          ${report.signed ? `
            <div style="text-align:center;color:var(--success);font-size:12.5px;">${ICONS.done} ${en?'You have acknowledged this report.':'Anda telah mengesahkan laporan ini.'}</div>
          ` : `
            <label style="display:block;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.03em;color:var(--text-muted);margin-bottom:8px;">${en?'Sign to Acknowledge':'Tandatangan untuk Sahkan'}</label>
            <canvas id="insp-sig-pad" width="280" height="120" style="width:100%;max-width:280px;background:#fff;border-radius:6px;border:1px solid var(--border);touch-action:none;cursor:crosshair;display:block;margin:0 auto;"></canvas>
            <div style="display:flex;gap:8px;margin-top:8px;justify-content:center;">
              <button class="btn btn-outline btn-sm" data-action="clear-insp-sig-pad">${en?'Clear':'Kosongkan'}</button>
              <button class="btn btn-primary btn-sm" data-action="submit-inspection-signature">${en?'Confirm & Sign':'Sahkan & Tandatangan'}</button>
            </div>
          `}
        </div>
      </div>`;
  } else {
    body = `<p style="text-align:center;color:var(--text-muted);">${en?'Loading…':'Memuatkan…'}</p>`;
  }
  return `
  <div class="login-screen">
    <div class="login-box" style="max-width:380px;">
      <div class="login-brand">
        <div class="mark">${logoMarkHtml(112)}</div>
        <div class="sub">${en?'Vehicle Inspection Report':'Laporan Pemeriksaan Kenderaan'}</div>
      </div>
      <div class="panel">${body}</div>
    </div>
  </div>`;
}

async function loadInspectionReport(){
  try{
    const { data, error } = await supabaseClient.rpc('kiosk_inspection_report', { p_job_id: state.inspectJobId, p_token: state.inspectToken });
    if(error) throw error;
    state.inspectReport = data || 'invalid';
  }catch(e){
    reportError(e, 'Muatkan laporan pemeriksaan gagal');
    state.inspectReport = 'invalid';
  }
  render();
}

function attachInspectionReportHandlers(){
  if(state.inspectReport==='loading' && !state.inspectReportLoading){
    state.inspectReportLoading = true;
    loadInspectionReport();
  }
  const sigPad = /** @type {HTMLCanvasElement} */ (document.getElementById('insp-sig-pad'));
  if(sigPad){
    const ctx = sigPad.getContext('2d');
    ctx.strokeStyle = '#1a1a1a'; ctx.lineWidth = 2; ctx.lineCap = 'round';
    let drawing = false;
    const getPos = (e)=>{
      const rect = sigPad.getBoundingClientRect();
      const cx = e.touches ? e.touches[0].clientX : e.clientX;
      const cy = e.touches ? e.touches[0].clientY : e.clientY;
      return {x: cx-rect.left, y: cy-rect.top};
    };
    const start = (e)=>{ drawing=true; const p=getPos(e); ctx.beginPath(); ctx.moveTo(p.x,p.y); e.preventDefault(); };
    const move = (e)=>{ if(!drawing) return; const p=getPos(e); ctx.lineTo(p.x,p.y); ctx.stroke(); e.preventDefault(); };
    const end = ()=>{ drawing=false; };
    sigPad.addEventListener('mousedown', start);
    sigPad.addEventListener('mousemove', move);
    window.addEventListener('mouseup', end);
    sigPad.addEventListener('touchstart', start, {passive:false});
    sigPad.addEventListener('touchmove', move, {passive:false});
    sigPad.addEventListener('touchend', end);
  }
  bindAction('clear-insp-sig-pad', ()=>{
    const canvas = /** @type {HTMLCanvasElement} */ (document.getElementById('insp-sig-pad'));
    if(canvas) canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);
  });
  bindAction('submit-inspection-signature', async ()=>{
    const en = state.language==='en';
    const canvas = /** @type {HTMLCanvasElement} */ (document.getElementById('insp-sig-pad'));
    if(!canvas) return;
    const signature = canvas.toDataURL('image/png');
    try{
      const { data, error } = await supabaseClient.rpc('kiosk_submit_inspection_signature', { p_job_id: state.inspectJobId, p_token: state.inspectToken, p_signature: signature });
      if(error) throw error;
      if(!data){ showToast(en?'Could not submit — the report may already be signed.':'Gagal hantar — laporan mungkin sudah ditandatangan.'); return; }
      state.inspectReport = { ...state.inspectReport, signed:true };
      render();
    }catch(e){
      reportError(e, 'Hantar tandatangan laporan pemeriksaan gagal');
      showToast(en?'Could not submit your signature. Check your connection and try again.':'Gagal hantar tandatangan. Semak sambungan anda dan cuba lagi.');
    }
  });
}
